# Generated by Django 6.0.3 on 2026-04-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0002_crawlrawdata_record_type_crawlrawdata_unique_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrawdata',
            name='unique_key',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True),
        ),
    ]
