# Generated by Django 6.0.3 on 2026-04-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawling', '0004_alter_crawlrawdata_unique_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crawltarget',
            options={'ordering': ['-priority', 'site', 'target_type', '-created_at'], 'verbose_name': '크롤링 대상', 'verbose_name_plural': '크롤링 대상 목록'},
        ),
        migrations.AddField(
            model_name='crawltarget',
            name='crawl_interval_minutes',
            field=models.PositiveIntegerField(default=60, help_text='이 target을 다시 수집할 최소 간격(분)'),
        ),
        migrations.AddField(
            model_name='crawltarget',
            name='priority',
            field=models.PositiveIntegerField(default=1, help_text='숫자가 클수록 우선 수집'),
        ),
        migrations.AlterField(
            model_name='crawlrawdata',
            name='item_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='crawlrawdata',
            name='page_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
