version: "3.9"

services:
  db:
    image: ankane/pgvector:v0.5.1
    container_name: product_review_postgres
    restart: always

    # [개발용] 개발 환경변수 파일 사용
    env_file:
      - .env.dev

    # [개발용] DB 컨테이너가 생성될 때 사용할 값
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    # [개발용] 로컬 PC에서 DB 확인하려고 5433으로 열어둠
    ports:
      - "5433:5432"

    volumes:
      - product_review_postgres_data:/var/lib/postgresql/data

    networks:
      - app-network

  redis:
    image: redis:7
    container_name: redis-server
    restart: always

    # [개발용] 로컬에서 redis-cli 등으로 확인 가능
    ports:
      - "6379:6379"

    networks:
      - app-network

  web:
    build: .
    container_name: drf-web

    # [개발용] Django 개발 서버 사용
    command: python manage.py runserver 0.0.0.0:8000

    restart: always

    # [개발용] 코드 변경 즉시 반영되도록 볼륨 마운트
    volumes:
      - .:/app

    ports:
      - "8000:8000"

    # [개발용] .env.dev 사용
    env_file:
      - .env.dev

    depends_on:
      - db
      - redis
      - fastapi

    networks:
      - app-network

  celery:
    build: .
    container_name: celery-worker

    # [개발용] Celery worker 실행
    command: celery -A mysite worker --loglevel=info --pool=solo

    restart: always

    # [개발용] 코드 변경 즉시 반영
    volumes:
      - .:/app

    # [개발용] .env.dev 사용
    env_file:
      - .env.dev

    depends_on:
      - db
      - redis
      - web
      - fastapi

    networks:
      - app-network

  fastapi:
    build:
      context: ../ai-server
    container_name: fastapi-server

    # [개발용] uvicorn 직접 실행
    command: uvicorn main:app --host 0.0.0.0 --port 8001

    restart: always

    # [개발용] 코드 변경 즉시 반영
    volumes:
      - ../ai-server:/app

    ports:
      - "8001:8001"

    networks:
      - app-network

  # Prometheus 모니터링
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-server
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
    depends_on:
      - web
      - fastapi
    networks:
      - app-network

  # Alertmanager 알림
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager-server
    restart: always
    ports:
      - "9093:9093"
    volumes:
      - ./prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - app-network

  # Grafana 시각화
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-server
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - app-network

volumes:
  product_review_postgres_data:
  grafana_data:

networks:
  app-network:
    driver: bridge
